### PR TITLE
Fix/new rnaseqs

### PR DESCRIPTION
**Pull request by MatBarba**
Addition and fixes of some RNA-seq tracks (missing or new).

### CODE REVIEW

**Comment by nicklangridge** [comment]
Do you need this on the branch also (i.e are these changes to go live?)

**Comment by MatBarba** [comment]
If possible, but I'd like to check on pre before.

**Comment by nicklangridge** [comment]
ok, won't be today - but hopefully be before the tues dev call

Date: Fri, 11 Mar 2016 01:22:33 -0800

**Comment by MatBarba** [comment]
Hi Nick,

Do you think you can do this soon? I checked the links, so it should be 
ok to have it on live.

Thanks,
Matthieu

**Comment by nicklangridge** [comment]
Updated on pre

**Comment by MatBarba** [comment]
Thanks Nick, everything is working as intended.

**Comment by nicklangridge** [comment]
Do you want it live?

**Comment by MatBarba** [comment]
Yes: there is one commit that fixes 2 currently missing track.

**Comment by nicklangridge** [comment]
Now live

**Pull request merged**
